/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/ui/UISceneLoading.lh
 */
export class UISceneLoadingBase extends Laya.GWidget {
    public phaseText!: Laya.GTextField;
    public sceneProgressText!: Laya.GTextField;
    public resourceProgressText!: Laya.GTextField;
    public progressFill!: Laya.GWidget;
    public percentText!: Laya.GTextField;
}

