/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/game/scenes/FrameworkDemo.ls
 */
export class FrameworkDemoSceneBase extends Laya.Scene {
}

