/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/scenes/Lobby.ls
 */
export class LobbySceneBase extends Laya.Scene {
    public uiRoot!: Laya.GWidget;
}

