/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UISceneLoading } from "../ui/UISceneLoading";

/**
 * bootstrap/scenes/Startup.ls
 */
export class StartupSceneBase extends Laya.Scene {
    public loadingView!: UISceneLoading;
}

