/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/game/ui/examples/FullscreenMid.lh
 */
export class ExampleFullscreenMidViewBase extends Laya.GWidget {
    public frame!: Laya.GLabel;
    public counterText!: Laya.GTextField;
    public actionButton!: Laya.GButton;
}

