/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { DynamicImage } from "../../../../../framework/presentation/ui/DynamicImage";

/**
 * bootstrap/game/ui/examples/InventoryItem.lh
 */
export class ExampleItemViewBase extends Laya.GButton {
    public indexText!: Laya.GTextField;
    public itemImage!: DynamicImage;
    public quantityText!: Laya.GTextField;
}

