/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/game/ui/examples/Confirmation.lh
 */
export class ExampleConfirmationViewBase extends Laya.GWidget {
    public frame!: Laya.GLabel;
    public messageText!: Laya.GTextField;
    public cancelButton!: Laya.GButton;
    public confirmButton!: Laya.GButton;
}

