/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/ui/examples/UIBattle.lh
 */
export class UIBattleBase extends Laya.GWidget {
    public frame!: Laya.GLabel;
    public counterText!: Laya.GTextField;
    public actionButton!: Laya.GButton;
}

