/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/ui/examples/UIConfirmation.lh
 */
export class UIConfirmationBase extends Laya.GWidget {
    public frame!: Laya.GLabel;
    public messageText!: Laya.GTextField;
    public cancelButton!: Laya.GButton;
    public confirmButton!: Laya.GButton;
}

