/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/ui/examples/UIInventory.lh
 */
export class UIInventoryBase extends Laya.GWidget {
    public frame!: Laya.GLabel;
    public summaryText!: Laya.GTextField;
    public midExampleButton!: Laya.GButton;
    public inventoryBadge!: Laya.GWidget;
    public inventoryBadgeCount!: Laya.GTextField;
    public itemList!: Laya.GList;
    public selectionText!: Laya.GTextField;
    public resetButton!: Laya.GButton;
    public useButton!: Laya.GButton;
}

