/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { UIDynamicImage } from "../../../../../framework/presentation/ui/UIDynamicImage";

/**
 * bootstrap/ui/examples/components/UIInventoryItem.lh
 */
export class UIInventoryItemBase extends Laya.GButton {
    public indexText!: Laya.GTextField;
    public itemImage!: UIDynamicImage;
    public quantityText!: Laya.GTextField;
}

