/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * bootstrap/ui/examples/UILobby.lh
 */
export class UILobbyBase extends Laya.GWidget {
    public statusText!: Laya.GTextField;
    public detailText!: Laya.GTextField;
    public examplesButton!: Laya.GButton;
    public inventoryBadge!: Laya.GWidget;
    public inventoryBadgeCount!: Laya.GTextField;
    public inventoryText!: Laya.GTextField;
    public rewardButton!: Laya.GButton;
    public feedbackText!: Laya.GTextField;
    public snapshotButton!: Laya.GButton;
    public replayButton!: Laya.GButton;
    public battleButton!: Laya.GButton;
}

